version: '3.6'
services:
  gitlab:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    hostname: '3.218.142.89'
    ports:
      - '50000:50000'
      - '8080:8080'
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    shm_size: '256'
